env: mmdp_game_1

env_args:
  n_agents: 2
  n_actions: 2
  reward_win: 1
  episode_limit: 100
  obs_last_action: False
  state_last_action: False
  print_rew: False
  is_print: False
  print_steps: 1000
learner_log_interval: 20000
log_interval: 20000
runner_log_interval: 20000
t_max: 10050000
test_interval: 20000
test_nepisode: 30
test_greedy: True
demo_interval: 20000
